import "./ui/global.css";
import {AuthContextProvider, BagProvider} from "@/app/context/providers";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
}

export default function RootLayout({children}) {
    return (
        <html lang={"en"} >
            <body className={"bg-grisclaro"}>
            <AuthContextProvider>
                <BagProvider>
                    {children}
                </BagProvider>
            </AuthContextProvider>
            </body>
        </html>
    )
}